name = "SimpleDelimitedFiles"
uuid = "44ac6da9-39e0-40c2-8ac2-dc1cb273e973"
authors = ["jishnub <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"

[compat]
Aqua = "0.5"
InvertedIndices = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Printf", "Test", "DelimitedFiles"]
